Avoid use of try, use respond_to? instead
Because Rails 3's `try` method behavior does not dance with its
successors:

Rails 3:

"".try(:call)
=> NoMethodError: undefined method `call' for "emoji":String

Rails 4+:

"".try(:call)
=> nil